### ISSUE TITLE
still necessary?

### ISSUE THREAD

**Issue by konne** [q2g/q2g-ext-selector#17]
see code line: 

https://github.com/q2g/q2g-ext-selector/blob/0382c671ee0787bfe9103f11eb5212664e6db19b/src/q2g-ext-selectorDirective.html#L4

**Comment by thomashaenig** [comment]
Hi,
i checked the code and did some small code quality fixes. 
The property “q2g-shortcut-scope” on a html element to specify the element as a root element for a local shortcut (the element in which subelements the focus should be) is still required. But this should not have to be an own directive, or even need a value, it just needs to be set as a property on a html element.

**Comment by konne** [comment]
1. please remove the directive and just use this as a html attribute
2. q2g-shortcut-scope as stopper is great
3. q2g-shortcut-scope="NAME" as NAMED stopper is also great
