### ISSUE TITLE
qlik.navigation.getMode() is not working in Mashups

### ISSUE THREAD

**Issue by thomashaenig** [q2g/q2g-ext-selector#23]
### Description

qlik.navigation.getMode() did not work in mashups, because there is no qlik import available

##### Expected behavior

get the qlik.navigation.getMode() from other source

**Comment by konne** [comment]
please remove from the q2g-ext-selectorDirective.ts and move to the q2g-ext-selector.ts.
We can handle it also over a service or an attribute, but I prefer the attribute.
