### ISSUE TITLE
invalid visualization message

### ISSUE THREAD

**Issue by zucoa** [q2g/q2g-ext-selector#36]
Hello - unzipped the extension to the extensions directory, then attempted to drag and drop into a sheet, but get an "Invalid Visualization" message and unable to edit further. I have Qlik Sense Nov. 2017 release.

**Comment by konne** [comment]
Hi,
do you used this download link?

https://m.sense2go.net/extension-package

If you just donwload the REPO from github as Zip, this is not working, because this is typescript code and this have to compiled.

bye Konrad

**Comment by thomashaenig** [comment]
@konne please close
